### ISSUE TITLE
translation into Portuguese "PT"

### ISSUE THREAD

**Issue by bilton30** [Zakarialabib/myStockMaster#103]
Could improve the translation of the platform into Portuguese "PT-BR" is currently translating according to English

**Comment by Zakarialabib** [comment]
Translation could be done very easily, but exact technical words, especially in business context could be tricky, if u a a native speaker, open a pr and contribute

**Comment by bilton30** [comment]
I'm a native Portuguese speaker, I'll open a PR as soon as possible

**Comment by Zakarialabib** [comment]
great 👍
