### ISSUE TITLE
issude detected Messaging 

### ISSUE THREAD

**Issue by yakshdeveloper** [Zakarialabib/myStockMaster#112]
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/ab53fa08-6d54-4c4d-b49c-daa30ff714fa)

**Comment by yakshdeveloper** [comment]
??

**Comment by Zakarialabib** [comment]
@yakshdeveloper describe the issue or suggest improvements with a pr .

**Comment by yakshdeveloper** [comment]
Somthing went wrong there

**Comment by yakshdeveloper** [comment]
I will update list

**Comment by yakshdeveloper** [comment]
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/66e03683-8e8b-473b-8a69-ad9070d2ebc2)
