### ISSUE TITLE
All module issue screenshots 

### ISSUE THREAD

**Issue by yakshdeveloper** [Zakarialabib/myStockMaster#133]
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/a8761fec-b4c5-4edb-bf90-21c956024434)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/4626e1ae-7b2f-4f9d-963a-099516fc9cf7)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/c6f4d381-febb-4cee-bc1a-77ca37ca3f12)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/80a2f5e3-d55c-4745-ab88-63f88b3cc0b2)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/99d89128-623d-4e37-81f6-2c02ea19d4f7)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/aaf0e803-9858-4705-a7e4-6c0011b27a88)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/41a9db75-5e36-417e-8b76-00c3b3e4562d)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/e7d252bc-0fb2-47a2-b200-8251c79db959)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/a119ec82-fad9-4113-963f-77891082f3d4)
![image](https://github.com/Zakarialabib/myStockMaster/assets/62012450/9d153909-4cc5-4d97-b0b0-e1958c277f5a)

**Comment by elmarzouguidev** [comment]
@yakshdeveloper can explain to us what happen here
