### ISSUE TITLE
Migration is not running 

### ISSUE THREAD

**Issue by BabarEplanet** [Zakarialabib/myStockMaster#153]
**Describe the bug**
Migration is not running 

**To Reproduce**
1. php artisan migrate --seed

**Expected behavior**
Errior and variable 

**Screenshots**
![image](https://github.com/Zakarialabib/myStockMaster/assets/157487308/c1022b84-967f-470d-85bf-3907256225b8)

**Comment by ithinktechonline** [comment]
I did the solution in this link and it works [https://github.com/spatie/laravel-permission/issues/2577](https://github.com/spatie/laravel-permission/issues/2577)

**Comment by hidjrahs** [comment]
> This is the solution
> 
> 1. delete the `database\migrations\2021_01_14_192129_create_permission_tables.php`
> 2. `php artisan vendor:publish` select 41 which is the **permission-migrations** tag then hit **Enter**
> 3. ````php artisan migrate --seed```

Thanks it is work for me
