### ISSUE TITLE
 SQLSTATE[HY000]: General error: 1005 Can't create table `mystockmaster`.`expenses` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `expenses` add constraint `expenses_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete restrict)

### ISSUE THREAD

**Issue by Ishakkangah** [Zakarialabib/myStockMaster#178]
**Describe the bug**
 SQLSTATE[HY000]: General error: 1005 Can't create table `mystockmaster`.`expenses` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `expenses` add constraint `expenses_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete restrict)

I have a problem when I run the php artisan migrate --seed command as above, help me please

**Comment by mostafa-amine** [comment]
Try to refresh the database please: `php artisan migrate:fresh --seed`

**Comment by Ishakkangah** [comment]
I can do php artisan migrate:fresh --seed , but do not work

Pada Sab, 22 Jun 2024 18.58, mostafa amine briere ***@***.***>
menulis:

**Comment by nuovo10** [comment]
translated with google

I have the same problem too:


![imagen](https://github.com/Zakarialabib/myStockMaster/assets/88532456/0c0c70c3-3d93-4791-b8a9-4f115f1e931c)

**Comment by bryanagamk** [comment]
Follow the dataType to resolve these issues.
I change the line 
`$table->foreignIdFor(User::class)->nullable()->constrained()->restrictOnDelete();`

into this line 

`$table->uuid('user_id');`

`$table->foreign('user_id')->references('id')->on('users')->onDelete('restrict');`

**Comment by nuovo10** [comment]
Thansks.

Good afternoon.
Now this table migrates successfully
