### ISSUE TITLE
Class "CustomerGroup" not found

### ISSUE THREAD

**Issue by nuovo10** [Zakarialabib/myStockMaster#182]
Good afternoon.
Another error when migrating tables

![imagen](https://github.com/Zakarialabib/myStockMaster/assets/88532456/275b153d-863a-428c-a995-aefb4a382c7e)

**Comment by jurandircod** [comment]
No arquivo: **2021_07_29_165419_create_customers_table**
importe a classe no topo do codigo assim: **use App\Models\CustomerGroup;**

**Comment by nuovo10** [comment]
now, Another 

![imagen](https://github.com/Zakarialabib/myStockMaster/assets/88532456/66687a01-b96e-4f0b-90f2-38d6fa017d75)
