### ISSUE TITLE
Call to undefined relationship [warehouses] on model [App\Models\Product]

### ISSUE THREAD

**Issue by krutsednar** [Zakarialabib/myStockMaster#58]
Error ```Call to undefined relationship [warehouses] on model [App\Models\Product].``` when I click POS

![image](https://user-images.githubusercontent.com/30821330/233234186-49cfb644-f9b2-4f38-8a99-7c1e031d37c8.png)

**Comment by Zakarialabib** [comment]
bug fixed , in later commits
