### ISSUE TITLE
syntax error, unexpected identifier "SaleStatus","PurchaseStatus"...

### ISSUE THREAD

**Issue by abubekers** [Zakarialabib/myStockMaster#59]
hello developers how are you doing hoping ou are doing well really i appreciate your strong effort and Optmisticness guys when i try to open sales,purchase and others i face this issues what happen any one pls can you tell me thanks in advance!

**Comment by abubekers** [comment]
hello please any one can you let me know please

**Comment by chrisoemma** [comment]
I am facing same issue did you solve it?

**Comment by Zakarialabib** [comment]
i guess the issue isnt happening now, anyway , ive upgraded the usage of Enums throughout the app
