### ISSUE TITLE
Translate Language & Convert To Rupiah Currency

### ISSUE THREAD

**Issue by Raichan4** [Zakarialabib/myStockMaster#79]
Hello Labib, it's me Raichan in linkedin was message you. Like you said before to create issue in your repository. So, would you want to instruct me to create translate in your project and i wanna add Rupiah currency in your project too.

**Comment by Zakarialabib** [comment]
hey,  so there is 2 places you could check to make that happen , in admin dashboard in settings , you will find languages and currencies, from there you can add your custom currency , the language part, is somehow tricky, you can add from the dashboard language, this will create json file from the default lang file, if you are familliar with laravel lang files , check the created one and translate it you could make it as your default language
