### ISSUE TITLE
Error With Routing 

### ISSUE THREAD

**Issue by fiikra** [Zakarialabib/myStockMaster#90]
Hi Thanks for sharing this great work , while trying your script i have found some issue like whene i call the purchases link the say ther is no ressources and i have cheched inside the route the purchaces is declared as ressources ans it call the controller normally i dont know where is the probléme  !

**Comment by Zakarialabib** [comment]
hey , can you tell how to reproduce the issue

**Comment by fiikra** [comment]
i have fixed the error after track the bug it takes me to /resources/views/livewire/sales/index.blade.php 
where there is a null condition which rederict every request to error page 500 
the solution is i have remove the empty condition on ligne 251 
 {{-- Sales Payment payment component   --}}
    @if (empty($showPayments))
        <livewire:sales.payment.index :sale="$sale" />
    @endif

and so for the purchases page 
i hope my contribution is helpfull

**Comment by Zakarialabib** [comment]
thank you bro , for mentioning it, i guess it already fixed in later pr,
